name: Upload packages to TestPyPI

on:
  push:
    branches:
      - master
      - next
    paths:
      - sphinx_revealjs/**
      - tools/**
      - README.rst
      - pyproject.toml
      - poetry.lock
      - setup.cfg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install poetry
      - name: Build package
        run: |
          if [ "$GITHUB_REF" = "refs/heads/next" ] ; then
            python tools/bump_extra_version.py dev
          else
            python tools/bump_extra_version.py post
          fi
          poetry run python tools/fetch_revealjs.py
          poetry build
      - name: Publish test pypi
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config http-basic.testpypi $PYPI_USERNAME $PYPI_PASSWORD 
          poetry publish -r testpypi
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
